# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c7d3808eee057b62f88c77d6213efb5f"
name = "Navegacion Mejorada"
application_url = "https://goal-survive-brand-sherman.trycloudflare.com"
embedded = true
handle = "navegacion-mejorada"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://goal-survive-brand-sherman.trycloudflare.com/auth/callback", "https://goal-survive-brand-sherman.trycloudflare.com/auth/shopify/callback", "https://goal-survive-brand-sherman.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
