# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c7d3808eee057b62f88c77d6213efb5f"
name = "Navegacion Mejorada"
application_url = "https://example.com" # Shopify reemplazará esto automáticamente al instalar
embedded = true
handle = "navegacion-mejorada"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

# --- PERMISOS CORREGIDOS ---
# Tu app necesita permisos para leer y escribir temas, no productos.
[access_scopes]
scopes = "write_themes,read_themes"

# --- URLS DE AUTENTICACIÓN LIMPIAS ---
[auth]
redirect_urls = [
  "https://example.com/api/auth/callback"
]

# --- WEBHOOKS ACTUALIZADOS Y COMPLETOS ---
[webhooks]
api_version = "2024-07"

  # Webhooks existentes
  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  # Webhooks obligatorios para cumplimiento de privacidad
  [[webhooks.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

[pos]
embedded = false
