# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "564898bcf6b32ae14577cf737b47196b"
name = "Navegación Mejorada KZD"
application_url = "https://example.com/"
embedded = true
handle = "navegacion-mejorada-kzd"

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false

[build]
include_config_on_deploy = true
