client_id = "c7d3808eee057b62f88c77d6213efb5f"
name = "Navegacion Mejorada"
application_url = "https://firewire-haiti-ac-metabolism.trycloudflare.com"
embedded = true
handle = "navegacion-mejorada"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[access_scopes]
# Permisos para leer y escribir en temas
scopes = "write_themes,read_themes"

[auth]
redirect_urls = [
  "https://firewire-haiti-ac-metabolism.trycloudflare.com/auth/callback",
  "https://firewire-haiti-ac-metabolism.trycloudflare.com/auth/shopify/callback",
  "https://firewire-haiti-ac-metabolism.trycloudflare.com/api/auth/callback"
]

# --- CONFIGURACIÓN DE WEBHOOKS CORRECTA ---
[webhooks]
api_version = "2024-07"

  # Webhook de desinstalación
  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  # Webhooks de privacidad agrupados
  [[webhooks.subscriptions]]
  uri = "/webhooks" # Una sola ruta para todos los webhooks de privacidad
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[pos]
embedded = false
