# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c7d3808eee057b62f88c77d6213efb5f"
name = "Navegacion Mejorada"
application_url = "https://example.com" # Shopify reemplaza esto automáticamente.
embedded = true
handle = "navegacion-mejorada"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

# --- PERMISOS REQUERIDOS ---
[access_scopes]
scopes = "write_themes,read_themes"

# --- URLS DE AUTENTICACIÓN ---
[auth]
redirect_urls = [
  "https://example.com/api/auth/callback"
]

# --- WEBHOOKS GENERALES ---
[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

# --- SECCIÓN ESPECIAL PARA WEBHOOKS OBLIGATORIOS ---
[app.gdpr_webhooks]
customers_data_request_url = "https://example.com/webhooks/customers/data_request"
customers_redact_url = "https://example.com/webhooks/customers/redact"
shop_redact_url = "https://example.com/webhooks/shop/redact"

[pos]
embedded = false
