client_id = "c7d3808eee057b62f88c77d6213efb5f"
name = "Navegacion Mejorada"
application_url = "https://example.com"
embedded = true
handle = "navegacion-mejorada"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[access_scopes]
scopes = "write_themes,read_themes"

[auth]
redirect_urls = [
  "https://example.com/api/auth/callback"
]

# --- TODOS LOS WEBHOOKS DECLARADOS JUNTOS ---
[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

[pos]
embedded = false
