# Este es el nombre de tu aplicación en el panel de Shopify.
name = "Navegacion Mejorada"
client_id = "c7d3808eee057b62f88c77d6213efb5f"

# Estos son los permisos que tu app solicita a los comerciantes.
access_scopes = {
  scopes = "write_themes,read_themes"
}

# Configuración de la autenticación.
auth = {
  redirect_urls = [
    "https://example.com/api/auth/callback",
    "https://example.com/api/auth/shopify/callback",
    "https://example.com/api/auth/callback/offline"
  ]
}

# ---- AQUÍ VA TU CONFIGURACIÓN DE WEBHOOKS ----
[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  # INICIO DE WEBHOOKS OBLIGATORIOS
  [[webhooks.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"
  # FIN DE WEBHOOKS OBLIGATORIOS

# Define las extensiones que forman parte de esta aplicación.
[pos]
embedded = false
